local opts = { noremap = true, silent = true }

-- Shorten function name
local keymap = vim.api.nvim_set_keymap
local vimkeymap = vim.keymap.set

-- Delete ending whitespaces
keymap('n', 'ge', ":lua require('user.functions').DeleteEndingWhiteSpace()<cr>", opts)

-- redirect to a popup focused window the messages generated by a command
vimkeymap("c", "<S-Enter>", function()
  require("noice").redirect(vim.fn.getcmdline())
  end, { desc = "Redirect Cmdline" })

-- Create a command alias for CopilotChat
vim.cmd("command! -nargs=1 CC lua require('user.functions').copilot_chat_with_text(<q-args>)")
